# Cambiar el puerto al 8082
server.port=8082

# Conexión a tu base de datos de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=postgres
spring.datasource.password=flores

# Configuración de Hibernate para actualizar las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=reservas